exam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('examination/', include('examination.urls')),
    path('admin/', admin.site.urls),
]

examination/urls.py
from django.urls import path
from . import views

app_name = 'examination'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    #path('<int:question_id>/Answer/', views.Answer, name='Answer'),
]

examination/models.py
import datetime
from django.db import models
from django.utils import timezone


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    email = models.EmailField(max_length=70,blank=True)
    age = models.PositiveIntegerField()

    def __str__(self):
    	return self.first_name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
    	return self.question_text



class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

examination/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Answer, Question,Person
from django.views import generic
from django.template import loader
from django.urls import path


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'examination/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'examination/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = question.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'examination/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_answer.votes += 1
        selected_answer.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('examination:results', args=(question.id,)))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'examination/detail.html', {'question': question})

examination/templates/examination/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'examination:vote' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
    <label for="answer{{ forloop.counter }}">{{ answer.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Answer">
</form>

examination/templates/examination/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'examination/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'examination:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nothing is available.</p>
{% endif %}


{

examination/templates/examination/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for answer in question.answer_set.all %}
    <li>{{ answer.choice_text }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'examination:detail' question.id %}">Answer again?</a>